TRUNCATE TABLE students CASCADE;
TRUNCATE TABLE groups CASCADE;
TRUNCATE TABLE courses CASCADE;
TRUNCATE TABLE teachers CASCADE;
TRUNCATE TABLE rooms CASCADE;
TRUNCATE TABLE lectures CASCADE;
TRUNCATE TABLE courses_groups CASCADE;
TRUNCATE TABLE teachers_courses CASCADE;
